modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
issueTrackerURL = "https://github.com/Lizard-Of-Oz/Inventorio"
license = "Custom"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="https://github.com/Lizard-Of-Oz/Inventorio"

[[mixins]]
config = "inventorio.mixins.json"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cloth_config"
type = "required"
versionRange = "[13,)"
ordering = "NONE"
side = "CLIENT"